# Generated by Django 4.2.5 on 2023-10-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_hobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
