# Generated by Django 4.2.5 on 2023-10-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_hobby_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='image_alt',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
