# Generated by Django 4.2.5 on 2023-10-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_hobby_image_alter_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='image',
            field=models.ImageField(upload_to='hobby'),
        ),
    ]
